load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "mlp",
    srcs = ["mlp.cpp"],
    hdrs = ["mlp.h"],
    strip_include_prefix = "//transformer/mlp",
    visibility = ["//:__pkg__"],
)
