load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "attention",
    srcs = ["attention.cpp"],
    hdrs = ["attention.h"],
    strip_include_prefix = "//transformer/attention",
    visibility = ["//:__pkg__"],
)
